### ISSUE TITLE
how to install uis package?

### ISSUE THREAD

**Issue by thap2331** [stuartjcameron/data-tools#4]
Hi, I see that we do "import uis" to use this tool. However, I could not find any direction about installing uis package in your documentation. Could you please let us know about installing this package?

https://github.com/stuartjcameron/data-tools

**Comment by stuartjcameron** [comment]
`uis` is the name of the tool itself (the main module). I have added installation instructions. I haven't created a pip package as yet so you need to download manually and put the files in your working directory.
